name: Test Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from test workflow with id-token"
